// Generated by CoffeeScript 1.8.0
(function() {
  var cache, dust, exports, measure, render;

  dust = require('dustjs-linkedin');

  measure = require('./measure');

  cache = require('./cache');

  render = function(path, data, fn) {
    render = cache(path, function(source) {
      console.log("compiling");
      return dust.compileFn(source);
    });
    return measure.async(function(done) {
      return render(data, function(err, out) {
        console.log(err);
        fn(null, out);
        return done();
      });
    });
  };

  module.exports = exports = {
    render: render
  };

}).call(this);
