// Generated by CoffeeScript 1.8.0
(function() {
  var exports, measure;

  measure = function(message, fn, binding) {
    var diff, ms, result, time;
    if (!fn) {
      fn = message;
      message = "benchmark";
    }
    time = process.hrtime();
    result = fn.apply(binding);
    diff = process.hrtime(time);
    ms = (diff[0] * 1e9 + diff[1]) / 1000000;
    console.log("" + message + ": took %d nanoseconds", ms);
    return result;
  };

  measure.async = function(message, fn, binding) {
    var done, time;
    if (!fn) {
      fn = message;
      message = "benchmark";
    }
    time = process.hrtime();
    done = function() {
      var diff, ms;
      diff = process.hrtime(time);
      ms = (diff[0] * 1e9 + diff[1]) / 1000000;
      return console.log("" + message + ": took %d nanoseconds", ms);
    };
    return fn.apply(binding, [done]);
  };

  module.exports = exports = measure;

}).call(this);
