// Generated by CoffeeScript 1.8.0
(function() {
  var cache, exports, measure, ractive, render;

  ractive = require('ractive');

  measure = require('./measure');

  cache = require('./cache');

  render = function(path, data, fn) {
    var r, template;
    template = cache(path);
    r = null;
    measure(function() {
      return r = new ractive({
        template: template,
        data: data,
        stripComments: false
      });
    });
    return measure(function() {
      return fn(null, r.toHTML());
    });
  };

  module.exports = exports = {
    render: render
  };

}).call(this);
